language: go
os: linux
dist: bionic

stages:
  - smoke test
  - name: test
    if: branch = master

_smoke: &smoke
  stage: smoke test

_test: &test
  stage: test
  script: make test

jobs:
  include:

    - name: "lint"
      << : *smoke
      go: "1.15"
      install:
        - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1
      script: make lint
      
    - name: "vet"
      << : *smoke
      go: "1.14"
      script: make vet
      
    - name: "test_1.11"
      << : *test
      go: "1.11"

    - name: "test_1.12"
      << : *test
      go: "1.12"

    - name: "test_1.13"
      << : *test
      go: "1.13"

    - name: "test_1.14"
      << : *test
      go: "1.14"

    - name: "coverage"
      << : *test
      go: "1.14"
      script:
        - make coverage
        - bash <(curl -s https://codecov.io/bash)
      